import { ROOTS, CHORDS } from "./data.js";
import { rootC, buildChordTones } from "./theory.js";
import { playMidi, playChord } from "./audio.js";

// ========== Ear training: identify chord quality by listening ==========
let earQuestion=null,earAnswered=false,earStats={correct:0,total:0};
function earQualities(){return Number(document.getElementById("earLevel").value)===3?["major","minor","augmented","diminished"]:["major","minor"];}
function renderEarOptions(){const c=document.getElementById("earOptions");c.innerHTML="";earQualities().forEach(q=>{const b=document.createElement("button");b.className="btn secondary";b.textContent=CHORDS[q].label[0].toUpperCase()+CHORDS[q].label.slice(1);b.addEventListener("click",()=>answerEar(q));c.appendChild(b);});}
function newEarQuestion(){renderEarOptions();const level=Number(document.getElementById("earLevel").value),qualities=earQualities(),quality=qualities[Math.floor(Math.random()*qualities.length)],pool=ROOTS.filter(r=>["C","D","E","F","G","A","Bb","Eb","F#"].includes(r.id)),root=level===1?rootC:pool[Math.floor(Math.random()*pool.length)];earQuestion={root,quality,tones:buildChordTones(root,quality)};earAnswered=false;playChord(earQuestion.tones.map(t=>t.midi));document.getElementById("earFeedback").className="result-box";document.getElementById("earFeedback").textContent="Puedes repetir antes de responder.";document.getElementById("earRepeat").disabled=false;document.getElementById("earExplain").disabled=false;document.getElementById("earNext").disabled=true;}
function answerEar(answer){const box=document.getElementById("earFeedback");if(!earQuestion){box.className="result-box status-bad";box.textContent="Primero pulsa “Nuevo acorde”.";return;}if(earAnswered)return;earAnswered=true;earStats.total++;const correct=answer===earQuestion.quality;if(correct)earStats.correct++;box.className=`result-box ${correct?"status-good":"status-bad"}`;box.innerHTML=correct?`<strong>¡Correcto!</strong> Era ${earQuestion.root.latin} ${CHORDS[earQuestion.quality].label}.`:`<strong>No esta vez.</strong> Era ${earQuestion.root.latin} ${CHORDS[earQuestion.quality].label}. Escucha la pista para aislar la nota decisiva.`;document.getElementById("earNext").disabled=false;updateEarStats();}
function updateEarStats(){document.getElementById("earCorrect").textContent=earStats.correct;document.getElementById("earTotal").textContent=earStats.total;document.getElementById("earAccuracy").textContent=earStats.total?`${Math.round(earStats.correct/earStats.total*100)}%`:"—";}
document.getElementById("earNew").addEventListener("click",newEarQuestion);document.getElementById("earNext").addEventListener("click",newEarQuestion);document.getElementById("earRepeat").addEventListener("click",()=>earQuestion&&playChord(earQuestion.tones.map(t=>t.midi)));document.getElementById("earExplain").addEventListener("click",()=>{if(!earQuestion)return;const idx=["augmented","diminished"].includes(earQuestion.quality)?2:1,rootMidi=earQuestion.tones.find(t=>t.role===0)?.midi??earQuestion.tones[0].midi,decisive=earQuestion.tones.find(t=>t.role===idx)?.midi??earQuestion.tones[idx].midi;playMidi(rootMidi,.65,0);playMidi(decisive,.65,.65);playChord(earQuestion.tones.map(t=>t.midi),false,1.4);document.getElementById("earFeedback").innerHTML=`<strong>Pista:</strong> raíz, luego ${CHORDS[earQuestion.quality].roleLabels[idx]}, después el acorde. Fórmula: ${CHORDS[earQuestion.quality].intervals.join(" – ")}.`;});document.getElementById("earLevel").addEventListener("change",()=>{earQuestion=null;earAnswered=false;renderEarOptions();document.getElementById("earFeedback").textContent="Pulsa “Nuevo acorde” para empezar.";});renderEarOptions();
