import { ROOTS, CHORDS, PRACTICAL_ROOT_IDS } from "./data.js";
import { rootById, buildChordTones, chordSymbol, spellChord, inversionName } from "./theory.js";
import { playChord } from "./audio.js";
import { buildKeyboard, highlightChordOnKeyboard } from "./keyboard.js";
import { registerLabRenderer } from "./nav.js";

// ========== Lab mode: free exploration of chords ==========
const labRoot=document.getElementById("labRoot");
function populateLabRoots(){const mode=document.getElementById("labSpellingMode").value,previous=labRoot.value||"C",roots=mode==="practical"?ROOTS.filter(r=>PRACTICAL_ROOT_IDS.includes(r.id)):ROOTS; labRoot.innerHTML=""; roots.forEach(r=>labRoot.add(new Option(`${r.latin} / ${r.american}`,r.id))); labRoot.value=roots.some(r=>r.id===previous)?previous:"C";}
const qualitySelects=[document.getElementById("labQuality"),document.getElementById("compareA"),document.getElementById("compareB")];
Object.entries(CHORDS).forEach(([key,chord])=>qualitySelects.forEach(sel=>sel.add(new Option(chord.label[0].toUpperCase()+chord.label.slice(1),key))));
document.getElementById("labQuality").value="major"; document.getElementById("compareA").value="major"; document.getElementById("compareB").value="minor"; populateLabRoots(); buildKeyboard("labKeyboard",null);
function updateInversions(){const select=document.getElementById("labInversion"),quality=document.getElementById("labQuality").value,count=CHORDS[quality].intervals.length,previous=Number(select.value||0),labels=["Fundamental","Primera inversión","Segunda inversión","Tercera inversión"]; select.innerHTML=""; for(let i=0;i<count;i++)select.add(new Option(labels[i],i)); select.value=String(Math.min(previous,count-1));}
function renderLab(play=true,arpeggio=false){updateInversions(); const root=rootById(labRoot.value),quality=document.getElementById("labQuality").value,inversion=Number(document.getElementById("labInversion").value),chord=CHORDS[quality],tones=buildChordTones(root,quality,inversion),bass=tones[0],symbol=chordSymbol(root,quality,bass.american),spelled=spellChord(root,quality); highlightChordOnKeyboard("labKeyboard",tones); if(play)playChord(tones.map(t=>t.midi),arpeggio); document.getElementById("labNotes").innerHTML=tones.map((t,i)=>`<span class="note-chip role-${Math.min(t.role,3)}">${t.latin}<small>${t.degree}</small></span>${i<tones.length-1?'<span class="separator">+</span>':''}`).join(""); document.getElementById("labInfo").innerHTML=`<div class="info-item"><span>Símbolo</span><strong>${symbol}</strong></div><div class="info-item"><span>Raíz</span><strong>${root.latin}</strong></div><div class="info-item"><span>Bajo</span><strong>${bass.latin}</strong></div><div class="info-item"><span>Posición</span><strong>${inversionName(inversion,tones.length)}</strong></div><div class="info-item"><span>Fórmula</span><strong>${chord.degreeLabels.join(" – ")}</strong></div><div class="info-item"><span>Semitonos</span><strong>${chord.intervals.join(" – ")}</strong></div><div class="info-item"><span>Notas</span><strong>${tones.map(t=>t.latin).join(" – ")}</strong></div>`; const advanced=spelled.some(n=>Math.abs(n.accidental)>1); const mode=document.getElementById("labSpellingMode").value; document.getElementById("labExplanation").innerHTML=`<strong>${symbol}</strong> contiene ${spelled.map((n,i)=>`${n.latin} (${chord.roleLabels[i]})`).join(", ")}. En esta posición, <strong>${bass.latin}</strong> es el bajo. <br><span class="muted">Descripción orientativa: ${chord.feeling}; el contexto musical puede cambiar esa percepción.</span>${advanced?'<div class="callout">Esta grafía usa una alteración doble. Es correcta en teoría; el modo práctico prioriza raíces comunes, pero algunas familias avanzadas todavía pueden necesitarla.</div>':''}${mode==="advanced"?'<div class="callout info">Modo teórico avanzado: la escritura conserva estrictamente las letras de raíz, tercera, quinta y séptima.</div>':''}`;}
document.getElementById("labSpellingMode").addEventListener("change",()=>{populateLabRoots();renderLab(false);}); labRoot.addEventListener("change",()=>renderLab(false)); document.getElementById("labQuality").addEventListener("change",()=>{updateInversions();renderLab(false);}); document.getElementById("labInversion").addEventListener("change",()=>renderLab(false)); document.getElementById("labPlay").addEventListener("click",()=>renderLab(true,false)); document.getElementById("labArpeggio").addEventListener("click",()=>renderLab(true,true));
document.getElementById("playCompare").addEventListener("click",()=>{const root=rootById(labRoot.value),a=document.getElementById("compareA").value,b=document.getElementById("compareB").value,ta=buildChordTones(root,a),tb=buildChordTones(root,b); highlightChordOnKeyboard("labKeyboard",ta);playChord(ta.map(t=>t.midi));setTimeout(()=>{highlightChordOnKeyboard("labKeyboard",tb);playChord(tb.map(t=>t.midi));},1150); const max=Math.max(CHORDS[a].intervals.length,CHORDS[b].intervals.length),changes=[]; for(let i=0;i<max;i++){const x=CHORDS[a].intervals[i],y=CHORDS[b].intervals[i]; if(x===undefined||y===undefined)changes.push("cambia la cantidad de notas"); else if(x!==y)changes.push(`la nota ${i+1} cambia ${y-x>0?"+":""}${y-x} semitono${Math.abs(y-x)===1?"":"s"}`);} document.getElementById("compareExplanation").innerHTML=`<strong>${root.latin} ${CHORDS[a].label} → ${root.latin} ${CHORDS[b].label}</strong><br>${[...new Set(changes)].join("; ")||"Conservan la misma fórmula."}`;});

registerLabRenderer(renderLab);
updateInversions(); renderLab(false);
