import { PC_KEY_LABELS, ROOTS, CHORDS } from "./data.js?v=3";
import { spellChord, buildChordTones } from "./theory.js?v=3";
import { playChord } from "./audio.js?v=3";
import { buildKeyboard, clearKeyboard, togglePcSelection } from "./keyboard.js?v=3";

// ========== Practice mode: build and ear training challenges ==========
let buildSelected=new Set(),currentBuildChallenge=null,buildAttempts=0;
buildKeyboard("buildKeyboard",(midi,pc)=>{togglePcSelection("buildKeyboard",buildSelected,pc); document.getElementById("buildChallengeResult").className="result-box"; document.getElementById("buildChallengeResult").innerHTML=buildSelected.size?`<strong>Seleccionaste:</strong> ${[...buildSelected].sort((a,b)=>a-b).map(pc=>PC_KEY_LABELS[pc]).join(" · ")}`:"No hay notas seleccionadas.";});
function newBuildChallenge(){const roots=ROOTS.filter(r=>["C","D","E","F","G","A","B","F#","Bb","Eb"].includes(r.id)),qualities=["major","minor","diminished","augmented","sus2","sus4"],root=roots[Math.floor(Math.random()*roots.length)],quality=qualities[Math.floor(Math.random()*qualities.length)]; currentBuildChallenge={root,quality}; buildAttempts=0;buildSelected.clear();clearKeyboard("buildKeyboard");document.getElementById("buildChallengePrompt").innerHTML=`<div class="mission-title">Construye: ${root.latin} ${CHORDS[quality].label} (${root.american}${CHORDS[quality].short})</div><p>Usa la fórmula ${CHORDS[quality].degreeLabels.join(" – ")}.</p>`;document.getElementById("buildChallengeResult").className="result-box";document.getElementById("buildChallengeResult").textContent="Selecciona las notas del acorde.";}
document.getElementById("newBuildChallenge").addEventListener("click",newBuildChallenge);
document.getElementById("clearBuildSelection").addEventListener("click",()=>{buildSelected.clear();clearKeyboard("buildKeyboard");document.getElementById("buildChallengeResult").textContent="No hay notas seleccionadas.";});
document.getElementById("checkBuildChallenge").addEventListener("click",()=>{const box=document.getElementById("buildChallengeResult");if(!currentBuildChallenge){box.className="result-box status-bad";box.textContent="Primero genera un desafío.";return;} buildAttempts++;const correctPcs=new Set(CHORDS[currentBuildChallenge.quality].intervals.map(i=>(currentBuildChallenge.root.pc+i)%12)),correct=buildSelected.size===correctPcs.size&&[...correctPcs].every(pc=>buildSelected.has(pc)),notes=spellChord(currentBuildChallenge.root,currentBuildChallenge.quality).map(n=>n.latin);box.className=`result-box ${correct?"status-good":"status-bad"}`;if(correct){box.innerHTML=`<strong>¡Correcto!</strong> ${notes.join(" – ")}.`;playChord(buildChordTones(currentBuildChallenge.root,currentBuildChallenge.quality).map(t=>t.midi));}else if(buildAttempts===1){box.innerHTML=`<strong>Casi.</strong> Comprueba que incluiste la raíz ${currentBuildChallenge.root.latin} y la cantidad correcta de notas.`;}else if(buildAttempts===2){box.innerHTML=`<strong>Segunda pista:</strong> los semitonos desde la raíz son ${CHORDS[currentBuildChallenge.quality].intervals.join(" – ")}.`;}else{box.innerHTML=`<strong>Respuesta:</strong> ${notes.join(" – ")}. Vuelve a construirla antes de generar otro desafío.`;}});
