import { rootC, buildChordTones, chordSymbol } from "../theory.js";
import { playChord } from "../audio.js";
import { buildKeyboard, highlightChordOnKeyboard, highlightMidiRoles } from "../keyboard.js";
import { setLessonState } from "../nav.js";

// ========== Lesson 5: Chord inversions (root position, 1st, 2nd inversion) ==========
buildKeyboard("inversionKeyboard",null);
let currentInversionDemo=0, inversionChallenge=null, inversionCorrect=0, lastChallengeInv=null;
const fingerings={right:[[1,3,5],[1,2,5],[1,3,5]],left:[[5,3,1],[5,3,1],[5,2,1]]};
function updateFingering(){const hand=document.getElementById("inversionHand").value, handName=hand==="right"?"Mano derecha":"Mano izquierda"; document.getElementById("inversionFingering").innerHTML=`<strong>${handName}:</strong> dedos ${fingerings[hand][currentInversionDemo].join("–")} para practicar esta disposición de Do mayor de forma aislada.`;}
function renderInversionDemo(inv,markExplored=true){currentInversionDemo=Number(inv); if(markExplored)setLessonState(5,"explored"); const tones=buildChordTones(rootC,"major",inv); highlightChordOnKeyboard("inversionKeyboard",tones); playChord(tones.map(t=>t.midi)); const bass=tones[0]; document.querySelectorAll(".inversion-demo").forEach(b=>b.classList.toggle("secondary",Number(b.dataset.inversionDemo)!==currentInversionDemo)); document.getElementById("inversionInfo").innerHTML=`<div class="info-item"><span>Acorde</span><strong>Do mayor</strong></div><div class="info-item"><span>Raíz</span><strong>Do</strong></div><div class="info-item"><span>Bajo</span><strong>${bass.latin}</strong></div><div class="info-item"><span>Símbolo</span><strong>${chordSymbol(rootC,"major",bass.american)}</strong></div>`; updateFingering();}
document.querySelectorAll(".inversion-demo").forEach(b=>b.addEventListener("click",()=>renderInversionDemo(b.dataset.inversionDemo)));
document.getElementById("inversionHand").addEventListener("change",updateFingering);
function newInversionChallenge(){let inv; do{inv=Math.floor(Math.random()*3);}while(inv===lastChallengeInv); lastChallengeInv=inv; const tones=buildChordTones(rootC,"major",inv); inversionChallenge={inv,tones,bass:tones[0].american,symbol:chordSymbol(rootC,"major",tones[0].american)}; document.getElementById("inversionChallengeNotes").innerHTML=`Notas de grave a agudo: <strong>${tones.map(t=>t.latin).join(" – ")}</strong>`; document.getElementById("inversionChallengeResult").className="result-box"; document.getElementById("inversionChallengeResult").textContent="Identifica raíz, bajo y símbolo."; highlightChordOnKeyboard("inversionKeyboard",tones); playChord(tones.map(t=>t.midi));}
document.getElementById("newInversionChallenge").addEventListener("click",newInversionChallenge);
document.getElementById("checkInversionChallenge").addEventListener("click",()=>{const box=document.getElementById("inversionChallengeResult"); if(!inversionChallenge){box.className="result-box status-bad";box.textContent="Primero genera un desafío.";return;} const rootOk=document.getElementById("inversionRootAnswer").value==="C",bassOk=document.getElementById("inversionBassAnswer").value===inversionChallenge.bass,symbolOk=document.getElementById("inversionSymbolAnswer").value===inversionChallenge.symbol; if(rootOk&&bassOk&&symbolOk){inversionCorrect++; if(inversionCorrect===1)setLessonState(5,"practiced"); if(inversionCorrect>=2)setLessonState(5,"mastered"); document.getElementById("inversionChallengeDots").textContent=[0,1].map(i=>i<Math.min(inversionCorrect,2)?"●":"○").join(" "); box.className="result-box status-good"; box.innerHTML=inversionCorrect>=2?"<strong>¡Dominado!</strong> Diferenciaste raíz, bajo y símbolo en dos inversiones.":"<strong>Correcto.</strong> Resuelve otra disposición distinta.";} else {box.className="result-box status-bad"; box.innerHTML=`<strong>Revisa:</strong> ${!rootOk?"la raíz da el nombre al acorde. ":""}${!bassOk?"el bajo es la nota más grave. ":""}${!symbolOk?"la barra indica el bajo.":""}`;}});
document.getElementById("rightHandOnly").addEventListener("click",()=>{highlightMidiRoles("inversionKeyboard",[{midi:64,role:1},{midi:67,role:2},{midi:72,role:0}]); playChord([64,67,72]); document.getElementById("bothHandsResult").innerHTML="<strong>Solo mano derecha:</strong> Mi es la nota más grave, por lo que suena como C/E, primera inversión.";});
document.getElementById("bothHandsDemo").addEventListener("click",()=>{highlightMidiRoles("inversionKeyboard",[{midi:48,role:0},{midi:64,role:1},{midi:67,role:2},{midi:72,role:0}]); playChord([48,64,67,72]); document.getElementById("bothHandsResult").innerHTML="<strong>Con Do grave en la izquierda:</strong> el bajo global vuelve a ser Do. El acorde completo está en posición fundamental, aunque la derecha toque Mi–Sol–Do.";});
function showVoiceMap(lines,total,label){document.getElementById("voiceLeadingDiagram").innerHTML=`<strong>${label}</strong>${lines.map(([a,b,d])=>`<div class="voice-line"><strong>${a}</strong><span class="voice-arrow">→ ${d}</span><strong>${b}</strong></div>`).join("")}<div class="callout info compact-callout">Movimiento total aproximado: <strong>${total} semitonos</strong>.</div>`;}
document.getElementById("voiceLeadingRough").addEventListener("click",()=>{playChord([60,64,67]);setTimeout(()=>playChord([53,57,60]),1100);showVoiceMap([["Do","Fa","+5"],["Mi","La","+5"],["Sol","Do","+5"]],15,"Posiciones fundamentales");});
document.getElementById("voiceLeadingSmooth").addEventListener("click",()=>{playChord([60,64,67]);setTimeout(()=>playChord([60,65,69]),1100);showVoiceMap([["Do","Do","0"],["Mi","Fa","+1"],["Sol","La","+2"]],3,"Conexión C → F/C");});
renderInversionDemo(0,false);
