import { rootById, buildChordTones, chordSymbol } from "../theory.js?v=3";
import { playChordSmart as playChord } from "../audioSampled.js?v=7";
import { buildKeyboard, highlightChordOnKeyboard, highlightMidiRoles } from "../keyboard.js?v=6";
import { setLessonState } from "../nav.js?v=7";
import { renderMissionDots } from "../icons.js?v=3";
import { recordAttempt } from "../stats.js?v=1";

// ========== Lesson 5: Chord inversions (root position, 1st, 2nd inversion) ==========
const rootG = rootById("G");
buildKeyboard("inversionKeyboard",null);
let currentInversionDemo=0, inversionChallenge=null, inversionCorrect=0, lastChallengeInv=null;
const fingerings={right:[[1,3,5],[1,2,5],[1,3,5]],left:[[5,3,1],[5,3,1],[5,2,1]]};
function updateFingering(){const hand=document.getElementById("inversionHand").value, handName=hand==="right"?"Mano derecha":"Mano izquierda"; document.getElementById("inversionFingering").innerHTML=`<strong>${handName}:</strong> dedos ${fingerings[hand][currentInversionDemo].join("–")} para practicar esta disposición de Sol mayor de forma aislada.`;}
function renderInversionDemo(inv,markExplored=true){currentInversionDemo=Number(inv); if(markExplored)setLessonState(5,"explored"); const tones=buildChordTones(rootG,"major",inv); highlightChordOnKeyboard("inversionKeyboard",tones); playChord(tones.map(t=>t.midi)); const bass=tones[0]; document.querySelectorAll(".inversion-demo").forEach(b=>b.classList.toggle("secondary",Number(b.dataset.inversionDemo)!==currentInversionDemo)); document.getElementById("inversionInfo").innerHTML=`<div class="info-item"><span>Acorde</span><strong>Sol mayor</strong></div><div class="info-item"><span>Raíz</span><strong>Sol</strong></div><div class="info-item"><span>Bajo</span><strong>${bass.latin}</strong></div><div class="info-item"><span>Símbolo</span><strong>${chordSymbol(rootG,"major",bass.american)}</strong></div>`; updateFingering();}
document.querySelectorAll(".inversion-demo").forEach(b=>b.addEventListener("click",()=>renderInversionDemo(b.dataset.inversionDemo)));
document.getElementById("inversionHand").addEventListener("change",updateFingering);
function newInversionChallenge(){let inv; do{inv=Math.floor(Math.random()*3);}while(inv===lastChallengeInv); lastChallengeInv=inv; const tones=buildChordTones(rootG,"major",inv); inversionChallenge={inv,tones,bass:tones[0].american,symbol:chordSymbol(rootG,"major",tones[0].american)}; document.getElementById("inversionChallengeNotes").innerHTML=`Notas de grave a agudo: <strong>${tones.map(t=>t.latin).join(" – ")}</strong>`; document.getElementById("inversionChallengeResult").className="result-box"; document.getElementById("inversionChallengeResult").textContent="Identifica raíz, bajo y símbolo."; highlightChordOnKeyboard("inversionKeyboard",tones); playChord(tones.map(t=>t.midi));}
document.getElementById("newInversionChallenge").addEventListener("click",newInversionChallenge);
document.getElementById("checkInversionChallenge").addEventListener("click",()=>{const box=document.getElementById("inversionChallengeResult"); if(!inversionChallenge){box.className="result-box status-bad";box.textContent="Primero genera un desafío.";return;} const rootOk=document.getElementById("inversionRootAnswer").value==="G",bassOk=document.getElementById("inversionBassAnswer").value===inversionChallenge.bass,symbolOk=document.getElementById("inversionSymbolAnswer").value===inversionChallenge.symbol,allOk=rootOk&&bassOk&&symbolOk; recordAttempt("inversiones",allOk,"visual"); if(allOk){inversionCorrect++; if(inversionCorrect===1)setLessonState(5,"practiced"); if(inversionCorrect>=2)setLessonState(5,"mastered"); renderMissionDots(document.getElementById("inversionChallengeDots"),[0,1].map(i=>i<Math.min(inversionCorrect,2))); box.className="result-box status-good"; box.innerHTML=inversionCorrect>=2?"<strong>¡Dominado!</strong> Diferenciaste raíz, bajo y símbolo en dos inversiones.":"<strong>Correcto.</strong> Resuelve otra disposición distinta.";} else {box.className="result-box status-bad"; box.innerHTML=`<strong>Revisa:</strong> ${!rootOk?"la raíz da el nombre al acorde. ":""}${!bassOk?"el bajo es la nota más grave. ":""}${!symbolOk?"la barra indica el bajo.":""}`;}});
document.getElementById("rightHandOnly").addEventListener("click",()=>{highlightMidiRoles("inversionKeyboard",[{midi:59,role:1},{midi:62,role:2},{midi:67,role:0}]); playChord([59,62,67]); document.getElementById("bothHandsResult").innerHTML="<strong>Solo mano derecha:</strong> Si es la nota más grave, por lo que suena como G/B, primera inversión.";});
document.getElementById("bothHandsDemo").addEventListener("click",()=>{highlightMidiRoles("inversionKeyboard",[{midi:43,role:0},{midi:59,role:1},{midi:62,role:2},{midi:67,role:0}]); playChord([43,59,62,67]); document.getElementById("bothHandsResult").innerHTML="<strong>Con Sol grave en la izquierda:</strong> el bajo global vuelve a ser Sol. El acorde completo está en posición fundamental, aunque la derecha toque Si–Re–Sol.";});
function showVoiceMap(lines,total,label){document.getElementById("voiceLeadingDiagram").innerHTML=`<strong>${label}</strong>${lines.map(([a,b,d])=>`<div class="voice-line"><strong>${a}</strong><span class="voice-arrow">→ ${d}</span><strong>${b}</strong></div>`).join("")}<div class="callout info compact-callout">Movimiento total aproximado: <strong>${total} semitonos</strong>.</div>`;}
document.getElementById("voiceLeadingRough").addEventListener("click",()=>{playChord([60,64,67]);setTimeout(()=>playChord([53,57,60]),1100);showVoiceMap([["Do","Fa","-7"],["Mi","La","-7"],["Sol","Do","-7"]],21,"Posiciones fundamentales");});
document.getElementById("voiceLeadingSmooth").addEventListener("click",()=>{playChord([60,64,67]);setTimeout(()=>playChord([60,65,69]),1100);showVoiceMap([["Do","Do","0"],["Mi","Fa","+1"],["Sol","La","+2"]],3,"Conexión C → F/C");});
renderInversionDemo(0,false);
